import { v } from "convex/values";
import { mutation, query, internalMutation } from "./_generated/server";
import { getAuthUserId } from "@convex-dev/auth/server";
export const getMyProfile = query({ args: {}, handler: async (ctx) => { const userId = await getAuthUserId(ctx); if (!userId) return null; return await ctx.db.query("profiles").withIndex("by_user", (q) => q.eq("userId", userId)).first(); } });
export const createProfile = mutation({ args: { email: v.string(), fullName: v.optional(v.string()), avatarUrl: v.optional(v.string()) }, handler: async (ctx, args) => { const userId = await getAuthUserId(ctx); if (!userId) throw new Error("Not authenticated"); const existing = await ctx.db.query("profiles").withIndex("by_user", (q) => q.eq("userId", userId)).first(); if (existing) return existing._id; return await ctx.db.insert("profiles", { userId, email: args.email, fullName: args.fullName, avatarUrl: args.avatarUrl, plan: "free" }); } });
export const updateProfile = mutation({ args: { fullName: v.optional(v.string()), avatarUrl: v.optional(v.string()) }, handler: async (ctx, args) => { const userId = await getAuthUserId(ctx); if (!userId) throw new Error("Not authenticated"); const profile = await ctx.db.query("profiles").withIndex("by_user", (q) => q.eq("userId", userId)).first(); if (!profile) throw new Error("Profile not found"); await ctx.db.patch(profile._id, args); } });
export const updateSubscription = internalMutation({ args: { stripeCustomerId: v.string(), stripeSubscriptionId: v.string(), plan: v.union(v.literal("starter"),v.literal("growth"),v.literal("agency")) }, handler: async (ctx, args) => { const profile = await ctx.db.query("profiles").withIndex("by_stripe_customer", (q) => q.eq("stripeCustomerId", args.stripeCustomerId)).first(); if (!profile) return; await ctx.db.patch(profile._id, { plan: args.plan, stripeSubscriptionId: args.stripeSubscriptionId }); } });
export const cancelSubscription = internalMutation({ args: { stripeCustomerId: v.string() }, handler: async (ctx, args) => { const profile = await ctx.db.query("profiles").withIndex("by_stripe_customer", (q) => q.eq("stripeCustomerId", args.stripeCustomerId)).first(); if (!profile) return; await ctx.db.patch(profile._id, { plan: "free", stripeSubscriptionId: undefined }); } });
export const setStripeCustomerId = mutation({ args: { stripeCustomerId: v.string() }, handler: async (ctx, args) => { const userId = await getAuthUserId(ctx); if (!userId) throw new Error("Not authenticated"); const profile = await ctx.db.query("profiles").withIndex("by_user", (q) => q.eq("userId", userId)).first(); if (!profile) throw new Error("Profile not found"); await ctx.db.patch(profile._id, { stripeCustomerId: args.stripeCustomerId }); } });
